version: 2.1
jobs:
  build:
    docker:
      # https://hub.docker.com/r/circleci/node/tags
      - image: circleci/golang:latest-node
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: sudo apt-get update
      - run:
          name: Install packages
          command: sudo apt-get install -y shellcheck
      - run:
          name: Install golang packages
          command: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      - run:
          name: Install conftest
          command: |
            mkdir -p conftest
            cd conftest
            wget https://github.com/open-policy-agent/conftest/releases/download/v0.24.0/conftest_0.24.0_Linux_x86_64.tar.gz
            tar xzf conftest_0.24.0_Linux_x86_64.tar.gz
            chmod 755 conftest
            cd ..
      - run:
          name: Install Npm packages
          command: yarn
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - run:
          name: conftest
          command: conftest/conftest test package.json
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: License
          command: yarn check_license
      - run:
          name: Audit
          command: yarn audit_critical
