version: 2.1
jobs:
  sqlfluff:
    docker:
      - image: sqlfluff/sqlfluff:latest
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Check SQL
          command: sqlfluff lint test.sql
