version: 2.1
jobs:
  build:
    docker:
      # https://hub.docker.com/r/circleci/node/tags
      - image: circleci/node:10.22-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: License
          command: yarn check_license
