name: API version

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check API document version
        run: |
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          API_FILE=openapi3_example.yaml
          git diff --name-only master ${{ github.sha }} | grep "${API_FILE}"
          if [$? -eq 0]; then
            echo 'checking version'
            git diff master ${{ github.ref }} "${API_FILE}" | grep ' version: '
          fi
