name: API version

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check API document version
        run: |
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          API_FILE=openapi3_example.yaml
          found=`git diff --name-only "origin/master..${{ github.sha }}" | grep -c "${API_FILE}"`
          if ["$found" != "0"]; then
            echo 'checking version'
            git diff "origin/master..${{ github.ref }}" "${API_FILE}" | grep ' version: '
          else
            exit 0
          fi
